import Head from "next/head";
import Image from "next/image";
import Router from "next/router";
import PostCard from "@/components/PostCard";
import { useQuery, gql } from "@apollo/client";
import { Card, Grid, Loader } from "semantic-ui-react";
import SpinningLoader from "@/components/SpinningLoader";
const FETCH_POSTS_QUERY = gql`
  {
    getPosts {
      id
      body
      createdAt
      username
      likeCount
      likes {
        username
      }
      commentCount
      comments {
        id
        username
        createdAt
        body
      }
    }
  }
`;

export default function Home() {
  const { loading, data } = useQuery(FETCH_POSTS_QUERY);
  const posts = data?.getPosts;

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid centered>
          <Grid.Row className="page-title">
            <h1>Recent Post</h1>
          </Grid.Row>

          <Grid.Row>
            <Card.Group itemsPerRow={3} stackable>
              {loading || !posts ? (
                <SpinningLoader />
              ) : (
                posts.map((post) => <PostCard key={post.id} post={post} />)
              )}
            </Card.Group>
          </Grid.Row>
        </Grid>
      </main>
    </>
  );
}
