import Head from "next/head";
import PostCard from "@/components/PostCard";
import { useQuery } from "@apollo/client";
import { Card, Grid, Transition } from "semantic-ui-react";
import PostForm from "@/components/PostForm";
import { useStateContext } from "@/context/auth";
import { FETCH_POSTS_QUERY } from "@/utils/queries";

export default function Home() {
  const { user } = useStateContext();
  const { loading, data } = useQuery(FETCH_POSTS_QUERY);
  const posts = data?.getPosts;

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid centered>
          <Grid.Row className="page-title">
            <h1>Recent Post</h1>
          </Grid.Row>

          <Grid.Row>
            <Card.Group itemsPerRow={3} stackable>
              {user && (
                <Grid.Column>
                  <PostForm />
                </Grid.Column>
              )}
              {loading || !posts ? (
                <div>
                  <div className="ui segment">
                    <div className="ui active transition visible inverted dimmer">
                      <div className="content">
                        <div className="ui inverted text loader">Loading</div>
                      </div>
                    </div>
                    <img
                      src="https://react.semantic-ui.com/images/wireframe/short-paragraph.png"
                      className="ui image"
                    />
                  </div>
                </div>
              ) : (
                <Transition.Group>
                  {posts.map((post) => (
                    <PostCard key={post.id} post={post} />
                  ))}
                </Transition.Group>
              )}
            </Card.Group>
          </Grid.Row>
        </Grid>
      </main>
    </>
  );
}
